Blog App -validations and model specs.
MohammadYaser/blog-app pull request #5
Opened 2023-12-07 14:09 UTC by MohammadYaser

Pull Request: Model Validations and Unit Specs Addition 🧪✨
Changes Made
Added validations to enhance data integrity for the User and Post models. 🛡️
Implemented unit specs for all models' methods and validations. 🧪
Model Validations
User Model
Name must not be blank.
PostsCounter must be an integer greater than or equal to zero.
Post Model
Title must not be blank.
Title must not exceed 250 characters.
CommentsCounter must be an integer greater than or equal to zero.
LikesCounter must be an integer greater than or equal to zero.
Unit Specs
Implemented unit tests for all models' methods and validations.
Ensured that validations are working as expected.
Validations added to prevent invalid data entry and ensure data consistency.
Unit specs provide comprehensive coverage for models' behavior.
Testing
Ran unit specs to validate model methods and ensure they are error-free.
Manually tested validations in the 'rails console' to verify their functionality.
Next Steps
 Collaborate with team members for code review.
 Address any feedback received during the review process.
 Ensure all tests pass successfully.
completed

- [ ]  Validations added for User and Post models.
- [ ]  Unit specs implemented for all models' methods and validations.
- [ ]  README updated with relevant information.

Please review and allow merge.

Thank you! 🙌

2023-12-07 14:40 UTC, DammyShittu requested changes
Hi @MohammadYaser,

## Highlights
✔️ Passing tests

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-12-07 14:40 UTC, DammyShittu commented on spec/models/post_spec.rb
> +  end
- [ ] Kindly add test for `recent_comments` method.

2023-12-07 14:40 UTC, DammyShittu commented on spec/models/like_spec.rb
> +end
- [ ] Kindly add test for `increment_post_likes_counter` method.

2023-12-07 14:40 UTC, DammyShittu commented on spec/models/comment_spec.rb
> +end
- [ ] Kindly add test for the `increment_post_comments_counter` method in the Comment model file.

2023-12-08 20:21 UTC, cynthiainga approved these changes
Hi @MohammadYaser, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![](https://user-images.githubusercontent.com/69011963/151541305-67f4f8e4-c79e-4f9d-a6cf-2c7efc3102c6.gif)

## Highlights

- [ ] No linters errors ✔️ 
- [ ] Correct Gitflow ✔️ 
- [ ] Descriptive PR ✔️ 
- [ ] All requested changes are made ✔️ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were missed by the previous reviewer and addressing them will really improve your application._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-12-09 16:04 UTC, merged